# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Latticeworks
email: quinn.e.mortimer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The showcase and example site
  for the Latticeworks Sass-based layout generation system.
baseurl: ""
url: "https://latticeworks.github.io"
github_username:  modimore
# twitter_username: jekyllrb

# Build settings
markdown: kramdown

# Sass settings
sass:
  load_paths:
    - _sass
    - scss

# Page group information
defaults:
  -
    scope:
      path: "_features"
      type: "features"
    values:
      layout: "default"

collections:
  features:
    output: true
